import * as dynamoose from 'dynamoose';

export const ContactsSchema = new dynamoose.Schema({
  id: {
    type: String,
    hashKey: true,
  },
  first_name: String,
  last_name: String,
  email: String,
  phone_number: String,
  service: String,
  status: String,
  monthly_charge: Number,
  charge_per_billing_cycle: Number,
  amount_to_be_paid_this_month: Number,
  billing_cycle: String,
  cc_authorization_received: Boolean,
  twenty_five_deducted: Boolean,
  payment_one_received: Boolean,
  payment_two_received: Boolean,
  payment_three_received: Boolean,
  payment_four_received: Boolean,
  special_circumstance: String,
  scholarship_state: String,
  invoice_Month: String,
  date_funds_requested_by_btc: Date,
  date_funds_requested_by_family: Date,
  invoice_number: String,
  invoice_paid_date: Date,
  inquiry_received: Date,
  inquiry_note_from_parent: String,
  consult_date: Date,
  twenty_five_received: Boolean,
  scholarship_student: Boolean,
  scholarship_name: String,
  trial_date: Date,
  registration_sent: Date,
  registration_received: Date,
  title: String,
  currently_accepting_students: Boolean,
  // Deprecated: replaced by structured `availability` below. Kept so reads of
  // pre-existing records with free-text availability don't error.
  tutoring_availability: String,
  availability: {
    type: Array,
    schema: [
      {
        type: Object,
        schema: {
          days: { type: Array, schema: [String] },
          start_time: String,
          end_time: String,
        },
      },
    ],
  },
  zoom_link: String,
  hourly_rate: Number,
  hiring_inquiry_received: Date,
  interview_offer_sent: Date,
  interview_scheduled: Date,
  offer_sent: Date,
  onboarding_paperwork_received: Date,
  training_completed: Date,
  user_profile_created: Boolean,
  user_group: String,
});
